language: c++
# Theoretically, this would allow us to clone subdmoules in parallel, which is quite slow.
# However, travis's git submodule doesn't understand --jobs
#git:
#  submodules: false
#before_install:
#  - git submodule update --init --recursive --jobs=4
env:
  global:
    - MAKEFLAGS=-j3
  matrix:
    - BIT_FLAG=
    - BIT_FLAG=--32bit
script:
  - env
  - cat /proc/cpuinfo
  # We need --verbose or Travis thinks our build has stalled.
  - install/build_release.sh --verbose --skip_psol $BIT_FLAG
sudo: required
compiler:
  - gcc
notifications:
  email:
    - cheesy@google.com
